# Generated by Django 2.2 on 2019-05-06 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Delhijobsinfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Date', models.DateField()),
                ('Company', models.CharField(max_length=30)),
                ('Title', models.CharField(max_length=30)),
                ('Eligibility', models.CharField(max_length=30)),
                ('Address', models.CharField(max_length=30)),
                ('Email', models.EmailField(max_length=254)),
                ('PhoneNumber', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Hydjobsinfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Date', models.DateField()),
                ('Company', models.CharField(max_length=30)),
                ('Title', models.CharField(max_length=30)),
                ('Eligibility', models.CharField(max_length=30)),
                ('Address', models.CharField(max_length=30)),
                ('Email', models.EmailField(max_length=254)),
                ('PhoneNumber', models.IntegerField()),
            ],
        ),
    ]
